# This workflow will generate a PR for changes in dev into master for a skill

name: Pull to Master
on: 
  push:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  pull_changes:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: assign-review-action
        uses: delivery-much/actions-assigner@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team-reviewers: NeonDevs
